version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-sam-app-using-ruby"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qqifk1hncoma"
s3_prefix = "hello-world-sam-app-using-ruby"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
